environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PowerShellEdition: PowerShellCore
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PowerShellEdition: WindowsPowerShell
  snowflake:
    secure: 2/KrmaMSE+h1uoCEQ5oU9yPpghEd3MhsqaN+Yzoinwga9PLaXXh1cGMHklEzcJ7H

clone_folder: c:\projects\PSFolderSize

version: 0.1.0.{build}
skip_commits:
  message: /updated readme.*|update readme.*s/
build: off

#Kick off the CI/CD pipeline
test_script: 
  - ps:   if ($env:PowerShellEdition -eq 'WindowsPowerShell') { . .\build.ps1 -Task Test -UpdateModules } 
  - pwsh: if ($env:PowerShellEdition -eq 'PowerShellCore')    { . .\build.ps1 -Task Publish -UpdateModules }